name: Publish Nuget Package

# on: workflow_dispatch
on:
  push:
    tags:
      - '*.*.**'

jobs:
  public_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Version
        run: |
          sed -i -e 's/{{Version}}/${{ github.ref_name }}/' ./src/CleanTest.Framework.csproj
      - name: Pack
        run: |
          dotnet pack ./src -c Release -o .output
      - name: Publish
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push .output/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json
        
